# @name token
POST https://localhost:5001/api/login HTTP/1.1
Content-Type: application/json

{
    "Email": "adminuser@gmail.com",
    "Password": "P@ssw0rd"
}
###
GET https://localhost:5001/api/v1/Documents/info/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
GET https://localhost:5001/api/v1/Documents/download/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
GET https://localhost:5001/api/v1/Documents HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
DELETE https://localhost:5001/api/v1/Documents/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
POST https://localhost:5001/api/v1/Groups HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}

{
    "name": "test"
}
###
GET https://localhost:5001/api/v1/Groups HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
PUT https://localhost:5001/api/v1/Groups/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}

{
    "name": "test"
}
###
curl --location --request POST 'https://localhost:5001/api/v1/Documents/upload' \
--header 'Authorization: Bearer {{token.response.body.$.Data.JWToken}}' \
--form 'description="My document"' \
--form 'category="demo"' \
--form 'file=@"/C:/Users/Alvaro/Downloads/Backend Engineer Interview Project.pdf"'
###
GET https://localhost:5001/api/v1/documents/info/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
GET https://localhost:5001/api/v1/Documents?pagenumber=1&pagesize=2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
GET https://localhost:5001/api/v1/Groups?pagenumber=1&pagesize=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
POST https://localhost:5001/api/v1/accounts  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}

{
  "FirstName": "demo5",
  "LastName": "demo5",
  "Email": "demo5@demo5.com",
  "UserName": "demo5@demo5.com",
  "Password": "P@ssw0rd",
  "ConfirmPassword": "P@ssw0rd"
}
###
POST https://localhost:5001/api/v1/accounts/2/group/1  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}
###
POST https://localhost:5001/api/v1/accounts/8/role/1  HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token.response.body.$.Data.JWToken}}